data:
  id: dlwh/wikitext_103_detokenized
model:
  type: gpt2
  hidden_dim: 32
  num_heads: 4
  num_layers: 2
trainer:
  mp: f32
  num_train_steps: 100

  checkpointer:
    keep:
      - every: 50
    save_interval: 5m

  per_device_eval_parallelism: 1
  per_device_parallelism: 1
  train_batch_size: 32

  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
task:
  ul2r:
    task_configs:
      causal:
        type: c
      prefix:
        type: s
      x1:
        type: x
        mask_prob: 0.5
        mean_span_length: 3
      x2:
        type: x
        mask_prob: 0.15
        mean_span_length: 32
      r:
        type: r
        mask_prob: 0.15
        mean_span_length: 3
    task_probs:
      causal: 1.5
      prefix: 0.25
      x1: 0.125
      x2: 0.0625
      r: 0.0625
