data: !include data/openwebtext_source.yaml
model:
  type: gpt2
  hidden_dim: 1280
  num_heads: 20
  num_layers: 36
  seq_len: 1024
  gradient_checkpointing: true
  scale_attn_by_inverse_layer_idx: true
trainer:
  wandb:
    project: "levanter"
    tags: [ "openwebtext", "gpt2", "sophia-g"]

  num_train_steps: 200000
  mp: p=f32,c=bfloat16

optimizer:
  type: sophia-g
  learning_rate: 2E-4
  weight_decay: 0.15
