data: !include data/openwebtext_source.yaml
model:
  type: gpt2
  hidden_dim: 1536
  num_heads: 24
  num_layers: 48
  seq_len: 1024
  gradient_checkpointing: true
  scale_attn_by_inverse_layer_idx: true
trainer:
  wandb:
    project: "levanter"
    tags: [ "openwebtext", "gpt2"]

  mp: p=f32,c=bfloat16
  model_axis_size: 1
  per_device_parallelism: 2
  per_device_eval_parallelism: 8
optimizer:
  learning_rate: 1E-4
  weight_decay: 0.1
  min_lr_ratio: 0.1
task:
  ul2r:
    task_configs:
      causal:
        type: c
      prefix:
        type: s
      x1:
        type: x
        mask_prob: 0.5
        mean_span_length: 3
      x2:
        type: x
        mask_prob: 0.15
        mean_span_length: 32
      r:
        type: r
        mask_prob: 0.15
        mean_span_length: 3
    task_probs:
      causal: 0.5
      prefix: 0.25
      x1: 0.125
      x2: 0.0625
      r: 0.0625
