data:
  id: dlwh/wikitext_103_detokenized
  tokenizer: "EleutherAI/gpt-neox-20b"
  cache_dir: "gs://levanter-data/tokenized/wiki-fast/"
model:
  type: gpt2
  hidden_dim: 1024
  num_heads: 16
  num_layers: 24
  seq_len: 1024
  gradient_checkpointing: true
  scale_attn_by_inverse_layer_idx: true

initialize_from_hf: "gpt2-medium"
use_hf_model_config: true

trainer:
  wandb:
    project: "locked"
    tags: [ "openwebtext", "gpt2"]

  mp: p=f32,c=bfloat16
  model_axis_size: 1
  per_device_parallelism: -1
  train_batch_size: 32
  num_train_steps: 2000000
optimizer:
  learning_rate: 1E-6
  weight_decay: 0.1
  warmup: 0.01
  min_lr_ratio: 0.1

alpha: 0.1
