data:
  cache_dir: "gs://levanter-data/tokenized/pile-old/"
  tokenizer: "EleutherAI/gpt-neox-20b"

model:
  type: gpt2
  hidden_dim: 1024
  num_heads: 16
  num_layers: 24
  seq_len: 1024
  gradient_checkpointing: true
  scale_attn_by_inverse_layer_idx: true

initialize_from_hf: "gpt2-medium"
use_hf_model_config: true

trainer:
  wandb:
    project: "locked"
    tags: [ "openwebtext", "gpt2", "itest"]

  mp: p=f32,c=bfloat16
  model_axis_size: 1
  per_device_parallelism: -1

  train_batch_size: 1024
  # this is deliberately very small for testing
  num_train_steps: 100000
  max_eval_batches: 10
  steps_per_eval: 50
optimizer:
  learning_rate: 3E-4
  weight_decay: 0.01
  warmup: 0.01
