data: !include data/rpv1_llama.yaml
model:
  type: llama
  seq_len: 8192
  hidden_dim: 2048
  intermediate_dim: 32768
  num_layers: 18
  num_heads: 8
  num_kv_heads: 1
  use_flash_attention: True
  flash_attention_block_size: 2048
trainer:
  wandb:
    project: "levanter"
    tags: ["redpajama", "llama"]

  mp: p=f32,c=bfloat16
  train_batch_size: 1024
  per_device_parallelism: 8
  per_device_eval_parallelism: 16 # set a larger batch size for eval
  num_train_steps: 250000  # 3,000,000,000,000 / 4096 / 1024
  steps_per_eval: 1000
  max_eval_batches: 2
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
optimizer:
  learning_rate: 3E-4  # same as Llama2-7B
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  epsilon: 1E-5
  warmup: 2000
  min_lr_ratio: 0.1
