data:
  cache_dir: "gs://levanter-data/tokenized/llama70b/"
  tokenizer: "meta-llama/Llama-2-70b-hf"
  configs:
    arxiv:
      train_urls:
        - gs://levanter-data/pile-domains/arxiv/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/arxiv/val.jsonl.zst
    books2:
      train_urls:
        - gs://levanter-data/pile-domains/books2/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/books2/val.jsonl.zst
    books3:
      train_urls:
        - gs://levanter-data/pile-domains/books3/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/books3/val.jsonl.zst
    dm_math:
      train_urls:
        - gs://levanter-data/pile-domains/dm_math/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/dm_math/val.jsonl.zst
    enron:
      train_urls:
        - gs://levanter-data/pile-domains/enron/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/enron/val.jsonl.zst
    europarl:
      train_urls:
        - gs://levanter-data/pile-domains/europarl/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/europarl/val.jsonl.zst
    free_law:
      train_urls:
        - gs://levanter-data/pile-domains/freelaw/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/freelaw/val.jsonl.zst
    github:
      train_urls:
        - gs://levanter-data/pile-domains/github/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/github/val.jsonl.zst
    hackernews:
      train_urls:
        - gs://levanter-data/pile-domains/hackernews/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/hackernews/val.jsonl.zst
    nih:
      train_urls:
        - gs://levanter-data/pile-domains/nih/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/nih/val.jsonl.zst
    opensubtitles:
      train_urls:
        - gs://levanter-data/pile-domains/opensubtitles/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/opensubtitles/val.jsonl.zst
    owt2:
      train_urls:
        - gs://levanter-data/pile-domains/owt2/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/owt2/val.jsonl.zst
    pg_19:
      train_urls:
        - gs://levanter-data/pile-domains/pg_19/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/pg_19/val.jsonl.zst
    philpapers:
      train_urls:
        - gs://levanter-data/pile-domains/philpapers/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/philpapers/val.jsonl.zst
    pile_cc:
      train_urls:
        - gs://levanter-data/pile-domains/pile_cc/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/pile_cc/val.jsonl.zst
    pubmed_abs:
      train_urls:
        - gs://levanter-data/pile-domains/pubmed_abs/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/pubmed_abs/val.jsonl.zst
    pubmed_central:
      train_urls:
        - gs://levanter-data/pile-domains/pubmed_central/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/pubmed_central/val.jsonl.zst
    stack_exchange:
      train_urls:
        - gs://levanter-data/pile-domains/stack_exchange/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/stack_exchange/val.jsonl.zst
    ubuntu_irc:
      train_urls:
        - gs://levanter-data/pile-domains/ubuntu_irc/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/ubuntu_irc/val.jsonl.zst
    uspto:
      train_urls:
        - gs://levanter-data/pile-domains/uspto/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/uspto/val.jsonl.zst
    wiki_en:
      train_urls:
        - gs://levanter-data/pile-domains/wiki_en/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/wiki_en/val.jsonl.zst
    youtube_subtitles:
      train_urls:
        - gs://levanter-data/pile-domains/youtube_subtitles/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile-domains/youtube_subtitles/val.jsonl.zst
  train_weights:
    # these weights come from the paper https://arxiv.org/pdf/2101.00027.pdf
    pile_cc: 0.1811
    pubmed_central: 0.1440
    books3: 0.1207
    owt2: 0.0
    arxiv: 0.0896
    github: 0.0759
    free_law: 0.0612
    stack_exchange: 0.0513
    uspto: 0.0365
    pubmed_abs: 0.0307
    pg_19: 0.0217
    opensubtitles: 0.0155
    wiki_en: 0.0
    dm_math: 0.0124
    ubuntu_irc: 0.0088
    books2: 0.0075
    europarl: 0.0073
    hackernews: 0.0062
    youtube_subtitles: 0.0060
    philpapers: 0.0038
    nih: 0.0030
    enron: 0.0014
 
model:
  type: llama
  hidden_dim: 8192
  intermediate_dim: 28672
  num_layers: 80
  num_heads: 64
  num_kv_heads: 8
  seq_len: 4096

trainer:
  wandb:
    project: "levanter"
    tags: [ "llama70bfull"]

  mp: p=f32,c=bfloat16
  train_batch_size: 1024  # set for v4-64 TPU
  num_train_steps: 1000
  steps_per_eval: 50
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
optimizer:
  learning_rate: 1.2E-5  # set low for fine-tuning
  weight_decay: 0.1
  min_lr_ratio: 0.1

