data:
  cache_dir: "gs://levanter-data/tokenized/pile-old/"
  tokenizer: "mistralai/Mistral-7B-v0.1"
model:
  type: mistral
# TODO: uncomment this once we resolve the resource exhaustion issue
initialize_from_hf: "mistralai/Mistral-7B-v0.1"
use_hf_model_config: true
trainer:
  wandb:
    project: "levanter"
    tags: ["openwebtext", "mistral"]

  mp: p=f32,c=bfloat16
  train_batch_size: 16  # set for v4-64 TPU
  num_train_steps: 1000
  steps_per_eval: 50
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
optimizer:
  learning_rate: 1.2E-5  # set low for fine-tuning
  weight_decay: 0.1
  min_lr_ratio: 0.1
