data:
  id: dlwh/wikitext_103_detokenized
  cache_dir: "gs://levanter-data/tokenized/wiki-mistral/"
  tokenizer: "mistralai/Mistral-7B-v0.1"
model:
  type: mistral
# TODO: uncomment this once we resolve the resource exhaustion issue
initialize_from_hf: "teknium/OpenHermes-2.5-Mistral-7B" #"mistralai/Mistral-7B-v0.1"
use_hf_model_config: true
trainer:
  wandb:
    project: "levanter"
    tags: ["openwebtext", "mistral"]

  mp: p=f32,c=bfloat16
  train_batch_size: 64  # set for v4-64 TPU
  # only eval
  num_train_steps: 3
  steps_per_eval: 1
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
optimizer:
  # no updates
  learning_rate: 0 #1.2E-5  # set low for fine-tuning
  weight_decay: 0.0
  min_lr_ratio: 0.0
