data:
  train_urls:
    - "gs://marin-data/processed/fineweb/fw-v1.0/CC-MAIN-2023-50/000_00000/0_processed_html.jsonl.gz"
    - "gs://marin-data/processed/fineweb/fw-v1.0/CC-MAIN-2023-50/000_00000/100_processed_html.jsonl.gz"
    - "gs://marin-data/processed/fineweb/fw-v1.0/CC-MAIN-2023-50/000_00000/101_processed_html.jsonl.gz"
    - "gs://marin-data/processed/fineweb/fw-v1.0/CC-MAIN-2023-50/000_00000/102_processed_html.jsonl.gz"
    - "gs://marin-data/processed/fineweb/fw-v1.0/CC-MAIN-2023-50/000_00000/103_processed_html.jsonl.gz"
    - "gs://marin-data/processed/fineweb/fw-v1.0/CC-MAIN-2023-50/000_00000/104_processed_html.jsonl.gz"
    - "gs://marin-data/processed/fineweb/fw-v1.0/CC-MAIN-2023-50/000_00000/105_processed_html.jsonl.gz"
    - "gs://marin-data/processed/fineweb/fw-v1.0/CC-MAIN-2023-50/000_00000/106_processed_html.jsonl.gz"
    - "gs://marin-data/processed/fineweb/fw-v1.0/CC-MAIN-2023-50/000_00000/107_processed_html.jsonl.gz"
    - "gs://marin-data/processed/fineweb/fw-v1.0/CC-MAIN-2023-50/000_00000/108_processed_html.jsonl.gz"
    - "gs://marin-data/processed/fineweb/fw-v1.0/CC-MAIN-2023-50/000_00000/109_processed_html.jsonl.gz"
    - "gs://marin-data/processed/fineweb/fw-v1.0/CC-MAIN-2023-50/000_00000/10_processed_html.jsonl.gz"
    - "gs://marin-data/processed/fineweb/fw-v1.0/CC-MAIN-2023-50/000_00000/110_processed_html.jsonl.gz"
    - "gs://marin-data/processed/fineweb/fw-v1.0/CC-MAIN-2023-50/000_00000/111_processed_html.jsonl.gz"
    - "gs://marin-data/processed/fineweb/fw-v1.0/CC-MAIN-2023-50/000_00000/112_processed_html.jsonl.gz"
    - "gs://marin-data/processed/fineweb/fw-v1.0/CC-MAIN-2023-50/000_00000/113_processed_html.jsonl.gz"
    - "gs://marin-data/processed/fineweb/fw-v1.0/CC-MAIN-2023-50/000_00000/114_processed_html.jsonl.gz"
    
  validation_urls:
    - "gs://levanter-data/paloma/4chan_meta_sep/val/val*.jsonl.gz"
    - "gs://levanter-data/paloma/c4_100_domains/val/val*.jsonl.gz"
    - "gs://levanter-data/paloma/c4_en/val/val*.jsonl.gz"
    - "gs://levanter-data/paloma/dolma-v1_5/val/val*.jsonl.gz"
    - "gs://levanter-data/paloma/dolma_100_programing_languages/val/val*.jsonl.gz"
    - "gs://levanter-data/paloma/dolma_100_subreddits/val/val*.jsonl.gz"
    - "gs://levanter-data/paloma/falcon-refinedweb/val/val*.jsonl.gz"
    - "gs://levanter-data/paloma/gab/val/val*.jsonl.gz"
    - "gs://levanter-data/paloma/m2d2_s2orc_unsplit/val/val*.jsonl.gz"
    - "gs://levanter-data/paloma/m2d2_wikipedia_unsplit/val/val*.jsonl.gz"
    - "gs://levanter-data/paloma/manosphere_meta_sep/val/val*.jsonl.gz"
    - "gs://levanter-data/paloma/mc4/val/val*.jsonl.gz"
    - "gs://levanter-data/paloma/ptb/val/val*.jsonl.gz"
    - "gs://levanter-data/paloma/redpajama/val/val*.jsonl.gz"
    - "gs://levanter-data/paloma/twitterAAE_HELM_fixed/val/val*.jsonl.gz"
    - "gs://levanter-data/paloma/wikitext_103/val/val*.jsonl.gz"
  cache_dir: "gs://levanter-data/trace/olmo7b_fineweb/"
  tokenizer: "allenai/OLMo-7B-hf"

model:
  type: olmo
initialize_from_hf: "ahmedsqrd/olmo-7b-hf-step0"
use_hf_model_config: true

trainer:
  seed: 42
  checkpointer:
    keep:
      - every: 1
        until: 10
      - every: 10
        until: 20
      - every: 100
        until: 1000
      - every: 1000
        until: 5000
      - every: 10000
        until: 40000
  tracker:
    type: wandb
    project: "trace-train"
    tags: ["pile", "olmo", "web_comparison"]
  mp: p=f32,c=bfloat16
  model_axis_size: 1
  per_device_eval_parallelism: -1
  max_eval_batches: 2
  train_batch_size: 128
  num_train_steps: 50000
  steps_per_eval: 10
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"

optimizer:
# lr from code llama paper
  learning_rate: 1.2E-5
  weight_decay: 0.1
  min_lr_ratio: 0.1

hf_save_steps: 10000
hf_save_path: "gs://levanter-checkpoints/olmo_trace_hf/"  # TODO
